### ISSUE TITLE
Página Error

### ISSUE THREAD

**Issue by NopAngel** [Eyvarjgc/P0rtf0li0#1]
Holap buenas, buen Portfolio!, pero hay un problemita de UI/UX, lo qué pasa es qué se repite mucho el color gris, y ese color es medio aburrido, estaria muy bien qué tenga diferentes colores, y no un color solo, muy buen Portfolio y feliz día/tarde/noche :D (PD: soy fan de **TypeScript**, y estaría bueno qué pongas la página a **TypeScript**, pero no es tan necesario)

**Comment by Eyvarjgc** [comment]
Hola angel, Agradezo tu feedbak, He estado trabajando en el fondo para que sea mas llamativo. Sobre Typescript, probablemente en el futuro lo utilice en el Portfolio  :3
